-- Product technical document categories (TDS/MDS/COA and related)
ALTER TYPE "DocumentCategory" ADD VALUE IF NOT EXISTS 'SDS';
ALTER TYPE "DocumentCategory" ADD VALUE IF NOT EXISTS 'TECHNICAL_SPECIFICATION';
ALTER TYPE "DocumentCategory" ADD VALUE IF NOT EXISTS 'PRODUCT_SPECIFICATION';
ALTER TYPE "DocumentCategory" ADD VALUE IF NOT EXISTS 'QUALITY_CERTIFICATE';
ALTER TYPE "DocumentCategory" ADD VALUE IF NOT EXISTS 'TEST_CERTIFICATE';
ALTER TYPE "DocumentCategory" ADD VALUE IF NOT EXISTS 'COMPLIANCE_CERTIFICATE';
