/**
 * Centralized domain enums for application-layer use.
 * Prisma remains the source of truth for persistence enums.
 * Phase 3+ APIs should import from here or from generated Prisma enums —
 * never scatter string literals for lifecycle states.
 */

export enum RoleCode {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  PROCUREMENT_MANAGER = 'PROCUREMENT_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  COMPLIANCE_MANAGER = 'COMPLIANCE_MANAGER',
  CUSTOMER = 'CUSTOMER',
  SELLER = 'SELLER',
}

export enum PermissionCode {
  USER_READ = 'USER_READ',
  USER_WRITE = 'USER_WRITE',
  SELLER_READ = 'SELLER_READ',
  SELLER_APPROVE = 'SELLER_APPROVE',
  CUSTOMER_READ = 'CUSTOMER_READ',
  CUSTOMER_WRITE = 'CUSTOMER_WRITE',
  GRADE_READ = 'GRADE_READ',
  GRADE_WRITE = 'GRADE_WRITE',
  PRODUCT_READ = 'PRODUCT_READ',
  PRODUCT_WRITE = 'PRODUCT_WRITE',
  OFFER_CREATE = 'OFFER_CREATE',
  OFFER_UPDATE = 'OFFER_UPDATE',
  OFFER_APPROVE = 'OFFER_APPROVE',
  PURCHASE_REQUEST_CREATE = 'PURCHASE_REQUEST_CREATE',
  PURCHASE_REQUEST_APPROVE = 'PURCHASE_REQUEST_APPROVE',
  PROCUREMENT_MANAGE = 'PROCUREMENT_MANAGE',
  ORDER_READ = 'ORDER_READ',
  ORDER_UPDATE = 'ORDER_UPDATE',
  PAYMENT_READ = 'PAYMENT_READ',
  PAYMENT_APPROVE = 'PAYMENT_APPROVE',
  SHIPMENT_READ = 'SHIPMENT_READ',
  SHIPMENT_UPDATE = 'SHIPMENT_UPDATE',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_VERIFY = 'DOCUMENT_VERIFY',
  SETTLEMENT_READ = 'SETTLEMENT_READ',
  SETTLEMENT_APPROVE = 'SETTLEMENT_APPROVE',
  AUDIT_READ = 'AUDIT_READ',
  NOTIFICATION_MANAGE = 'NOTIFICATION_MANAGE',
}

export const REFERENCE_NUMBER_PREFIX = {
  OFFER: 'OFFER',
  PURCHASE_REQUEST: 'PR',
  PROCUREMENT: 'PROC',
  PURCHASE_ORDER: 'PO',
  ORDER: 'ORD',
  PAYMENT: 'PAY',
  PROFORMA: 'PI',
  SHIPMENT: 'SHP',
  SETTLEMENT: 'STL',
  INVOICE: 'INV',
  CREDIT_APPLICATION: 'CRA',
  CREDIT_ACCOUNT: 'CR',
  CREDIT_TRANSACTION: 'CTX',
} as const;
